name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    # pull_requestの場合はマージされてたら実行する
    # if: github.event.pull_request.merged == true
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ConsoleCalculator
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./ConsoleCalculator
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./ConsoleCalculator
