name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    # pull_requestの場合はマージされてたら実行する
    # if: github.event.pull_request.merged == true
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2.2.0
      with: 
        # SonarQubeレポートの関連性を向上させるため shallow clone 無効化
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./ConsoleCalculator
    
    - name: Sonarqube begin
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /o:someorg /k:somekey /d:sonar.login=${{ secrets.SONAR_TOKEN }} /s:../SonarQube.Analysis.xml

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./ConsoleCalculator
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings --logger:trx
      working-directory: ./ConsoleCalculator

    - name: Sonarqube end
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
